// <auto-generated />
using EmployeeDirectoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDirectoryAPI.Migrations
{
    [DbContext(typeof(EmployeeDirectoryAPIContext))]
    [Migration("20231214130158_Employees")]
    partial class Employees
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeDirectoryAPI.Model.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Department = "IT",
                            FirstName = "Anthony",
                            JobTitle = "SharePoint Practice Head",
                            LastName = "Morris",
                            Location = "Seattle"
                        },
                        new
                        {
                            ID = 2,
                            Department = "IT",
                            FirstName = "Helen",
                            JobTitle = "Operations Manager",
                            LastName = "Zimmerman",
                            Location = "Seattle"
                        },
                        new
                        {
                            ID = 3,
                            Department = "IT",
                            FirstName = "Joanthon",
                            JobTitle = "Product Manager",
                            LastName = "Smith",
                            Location = "Seattle"
                        },
                        new
                        {
                            ID = 4,
                            Department = "IT",
                            FirstName = "Tami",
                            JobTitle = "Lead Engineer",
                            LastName = "Hopkins",
                            Location = "Seattle"
                        },
                        new
                        {
                            ID = 5,
                            Department = "IT",
                            FirstName = "Franklin",
                            JobTitle = "Network Engineer",
                            LastName = "Humark",
                            Location = "Seattle"
                        },
                        new
                        {
                            ID = 6,
                            Department = "HR",
                            FirstName = "Angela",
                            JobTitle = "Talent Manager",
                            LastName = "Bailey",
                            Location = "Seattle"
                        },
                        new
                        {
                            ID = 7,
                            Department = "IT",
                            FirstName = "Robert",
                            JobTitle = "Software Engineer",
                            LastName = "Mitchell",
                            Location = "Seattle"
                        },
                        new
                        {
                            ID = 8,
                            Department = "UX",
                            FirstName = "Olivia",
                            JobTitle = "UI Designer",
                            LastName = "Watson",
                            Location = "India"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
